name: 'build docker images: VerneMQ'

on:
  #push:
  #  branches:
  #    - 'main'
  #    - 'master'
  workflow_dispatch:
  schedule:
    - cron: '45 5 25 * *'  # At 05:45 on day-of-month 25.

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${GITHUB_SHA::8}
          GITHUB_REPO=${GITHUB_REPOSITORY,,}
          GITHUB_REPO_SHORT=${GITHUB_REPO#*/}
          #DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPO_SHORT}
          DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/vernemq
          #REDHAT_QUAY_REPO=${{ secrets.REDHAT_QUAY_USERNAME }}/${GITHUB_REPO_SHORT}
          #REDHAT_QUAY_REPO=${{ secrets.REDHAT_QUAY_USERNAME }}/vernemq

          # Set output parameters to github action.
          echo ::set-output name=build_date::${BUILD_DATE}
          echo ::set-output name=build_date_numeric::${BUILD_DATE_NUMERIC}
          echo ::set-output name=commit_hash::${COMMIT_HASH}
          echo ::set-output name=github_repo::${GITHUB_REPO}
          echo ::set-output name=docker_repo::${DOCKER_REPO}
          #echo ::set-output name=redhat_quay_repo::${REDHAT_QUAY_REPO}

          # VerneMQ
          #RELEASE=$(curl -s https://api.github.com/repos/vernemq/docker-vernemq/releases/latest | grep 'tag_name' | cut -d\" -f4)
          #RELEASE=$(curl -s https://api.github.com/repos/vernemq/vernemq/releases/latest | grep 'tag_name' | cut -d\" -f4)
          #echo "VERNEMQ_VERSION=${RELEASE}"
          #VERNEMQ_VERSION=${RELEASE}
          VERNEMQ_VERSION="1.12.3"
          echo ::set-output name=vernemq_version::${VERNEMQ_VERSION}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub 
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Login to RED HAT Quay.io Container Registry
      #  uses: docker/login-action@v1
      #  with:
      #    registry: quay.io
      #    username: ${{ secrets.REDHAT_QUAY_USERNAME }}
      #    password: ${{ secrets.REDHAT_QUAY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./vernemq.alpine.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          build-args: |
            BUILD_DATE=${{steps.script.outputs.build_date}}
            VCS_REF=${{steps.script.outputs.commit_hash}}
            VERNEMQ_VERSION=${{steps.script.outputs.vernemq_version}}
          tags: |
            ghcr.io/${{steps.script.outputs.github_repo}}:${{steps.script.outputs.vernemq_version}}-alpine
            ghcr.io/${{steps.script.outputs.github_repo}}:latest-alpine
            docker.io/${{steps.script.outputs.docker_repo}}:${{steps.script.outputs.vernemq_version}}-alpine
            docker.io/${{steps.script.outputs.docker_repo}}:latest-alpine
          #  quay.io/${{steps.script.outputs.redhat_quay_repo}}:latest-alpine
